title: "Cybersecurity Writeups"
description: "Bug bounty & security labs writeups by xwal13"
theme: minima

# Optional: GitHub Pages settings
url: "https://xwal13.github.io"
baseurl: "/cybersecurity-writeups"  

include:
  - assets/css/style.css
