title: "Cybersecurity Writeups"
description: "Bug bounty & security labs writeups by xwal13"
theme: minima
baseurl: "/cybersecurity-writeups"
url: "https://xwal13.github.io"

# Custom head
include:
  - _includes/head-custom.html
